### PR TITLE
Initial commit to update publications

### PR DESCRIPTION
**Pull request by CalCraven**

### CODE REVIEW

**Comment by CalCraven** [comment]
Any reviewers should just be able to use this link to install and validate the changes to the webpages.
https://formulae.brew.sh/formula/http-server

**Comment by daico007** [comment]
Hey @CalCraven, I think this look goods. Can you also add the high-throughput screening paper (https://doi.org/10.1063/5.0080838). We can probably add the GMSO paper later.

**Comment by CalCraven** [comment]
@daico007 
think I got it!

**Review by daico007 — APPROVED** [review]
LGTM!

**Comment by CalCraven** [comment]
I think one is ready to merge

**Comment by CalCraven** [comment]
@daico007 ^

**Pull request merged**
