### PR TITLE
Add Additional publications

### PR DESCRIPTION
**Pull request by umesh-timalsina**
image

@daico007 , @justinGilmer. Could you guys please verify that if the order of these publications make sense.

### CODE REVIEW

**Comment by daico007** [comment]
Can we create two sections for these papers: 
1) Core papers: TRUE, mbuild, Foyer, and may be the new aiche papers @justinGilmer?
2) Papers around the ecosystems: the rest in chronicle order (latest paper on top)

**Comment by rmatsum836** [comment]
```Thompson, M.W., Matsumoto, R., Sacci, R.L., Sanders, N.C., Cummings, P.T., 2019. Scalable Screening of Soft Matter: A Case Study of Mixtures of Ionic Liquids and Organic Solvents. J. Phys. Chem. B 123, 1340–1347. https://doi.org/10.1021/acs.jpcb.8b11527``` appears twice.

**Comment by kjcoulter** [comment]
This paper should always be at the top.  It's the main paper for all to cite on MoSDeF work:
1. Cummings, P. T., MCabe, C., Iacovella, C. R., Ledeczi, A., Jankowski, E., Jayaraman, A., Palmer, J. C., Maginn, E. J., Glotzer, S. C., Anderson, J. A., Ilja Siepmann, J., Potoff, J., Matsumoto, R. A., Gilmer, J. B., DeFever, R. S., Singh, R. & Crawford, B., "Open‐source molecular modeling software in chemical engineering focusing on the Molecular Simulation Design Framework," AIChE J. 67, (2021). DOI: 10.1002/aic.17206

2. Butler, B., Ramasubramani, V., Anderson, J. & Glotzer, S., "HOOMD-blue version 3.0 A Modern, Extensible, Flexible, Object-Oriented API for Molecular Simulations," in PROC. 19th PYTHON Sci. CONF. (SCIPY 2020) 24–31 (2020). DOI: 10.25080/Majora-342d178e-004
3. Ramasubramani, V., Dice, B. D., Harper, E. S., Spellings, M. P., Anderson, J. A. & Glotzer, S. C., "freud: A software suite for high throughput analysis of particle simulation data," Comput. Phys. Commun. 254, 107275 (2020). DOI: 10.1016/j.cpc.2020.107275

**Comment by umesh-timalsina** [comment]
image

This is what it will look like now.I have removed the duplicate thanks @rmatsum836.

**Review by justinGilmer — APPROVED** [review]

**Pull request merged**
